version: '3'

services:
  build_env_boost:
    image: env_ore_test:latest
    cap_drop:
      - NET_RAW
    build:
      context: .
      dockerfile: Dockerfile-Test
      args:
        - debian_tag=${DEBIAN_TAG}
