version: '3'

services:
  build_env_boost:
    image: build_env_boost:${BOOST_TAG}
    build:
      context: .
      dockerfile: Dockerfile-Boost
      args:
        - boost_version=${BOOST_TAG}
        - boost_dir=boost_${BOOST_DIR}
        - num_cores=16
