version: '3'

services:
  env_quantlib:
    image: env_quantlib:${QL_TAG}
    build:
      context: ../
      dockerfile: Docker/Dockerfile-QuantLib
      args:
        - boost_version=${BOOST_TAG}
        - num_cores=${NUM_CORES}
