version: '3'

services:
  ore_app:
    image: ore_app:${ORE_TAG}
    cap_drop:
      - NET_RAW
    build:
      context: ../
      dockerfile: Docker/Dockerfile-multistage
      args:
        - debian_tag=${DEBIAN_TAG}
        - num_cores=${NUM_CORES}
        - cmake_build_type=${CMAKE_BUILD_TYPE}
