version: '3'

services:
  env_ore_debug:
    image: env_ore_debug:${ORE_TAG}
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE-Debug
      args:
        - quantlib_version=${QL_TAG}
        - num_cores=16
