version: '3'

services:
  restapi:
    image: restapi:latest
    networks:
      - postman
    ports:
      - "5001:5001"

  simplefileserver:
    image: simplefileserver:latest
    env_file:
      - docker-envfile.env
    environment:
      - INPUT_DIR=${INPUT_DIR:-./../Input}
      - OUTPUT_DIR=${OUTPUT_DIR:-./../Output}
    volumes:
      - "../entrypoint-simplefileserver.sh:/app/entrypoint-simplefileserver.sh"
      - "../simplefileserver.py:/app/simplefileserver.py"
      - "${INPUT_DIR:-./../Input}:/app/Input"
      - "${OUTPUT_DIR:-./../Output}:/app/Output"
    networks:
      - postman
    ports:
      - "5000:5000"

networks:
  postman:
